export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  "appname": "Simple Logistics",

  "button.save": "Save",
  "button.login": "Login",
  "button.signup": "Sign up",
  "button.apply": "Add request",
  "button.search": "Search",

  "lang.ru": "Русский",
  "lang.en": "English",

  "nav.home": "Home",
  "nav.about": "About",
  "nav.requests": "Requests",
  "nav.users": "Users",
  "nav.signin": "Sign in",
  "nav.signup": "Sign up",
  "nav.profile": "Profile",

  "footer.disigned": "Designed and built by",
  "footer.using": "Using",
  "footer.and": "and",
  "footer.lang": "Interface language:",
  "footer.link.git": "Github",
  "footer.link.fb": "Facebook",
  "footer.link.vk": "VK",
  "footer.link.about": "About",
  "footer.link.autor": "Andrei Radzetski",
  "footer.link.ng2": "AngularJS 2",
  "footer.link.bootstrap": "Bootstrap 3",

  "page.home.title": "Simple Logistics",
  "page.home.description": "Some text, which describes the project.",
  "page.home.tag.addRequest": "Add request",
  "page.home.tag.findRequest": "Find request",
  "page.home.tag.findUser": "Find user",
  "page.home.tag.about": "About system",
  "page.home.search": "Search:",
  "page.home.departure": "Departure",
  "page.home.departure-date": "Departure date",
  "page.home.destination": "Destination",
  "page.home.destination-date": "Destination date",

  "page.about.title": "About",
  "page.about.description": "Some text, which describes the section.",

  "page.users.title": "Users",
  "page.users.description": "Some text, which describes the section.",

  "page.login.title": "Login",
  "page.login.description": "Some text, which describes the section.",
  "page.login.login": "Login",
  "page.login.password": "Password",
  "page.login.remember": "Remember me",

  "page.join.title": "Join",
  "page.join.description": "Some text, which describes the section.",
  "page.join.info": "Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.Some text, which describes the section.",
  "page.join.firstName": "First name",
  "page.join.secondName": "Second name",
  "page.join.email": "Email",
  "page.join.phone": "Phone",
  "page.join.password": "Password",
  "page.join.passwordRepeat": "Repeat password",

  "page.requests.title": "Requests",
  "page.requests.description": "Some text, which describes the section.",

  "page.profile.title": "Profile",
  "page.profile.description": "Some text, which describes the section.",
  "page.profile.nav.info": "Info",
  "page.profile.nav.requests": "Requests",
  "page.profile.nav.messages": "Messages",
  "page.profile.nav.settings": "Settings",
  "page.profile.info.email": "Email",
  "page.profile.info.phone": "Phone",
  "page.profile.info.country": "Country",
  "page.profile.info.city": "City",
  "page.profile.info.language": "Language",
  "page.profile.info.additional": "Additional information",
  "page.profile.settings.firstName": "First name",
  "page.profile.settings.secondName": "Second name"
}