export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  "appname": "Simple Logistics",

  "button.save": "Save",
  "button.login": "Login",
  "button.signup": "Sign up",
  "button.apply": "Add request",
  "button.search": "Search",
  "button.next": "Next",
  "button.add": "Add",

  "palceholder.date": "yyyy-mm-dd",

  "dict.language.label": "Язык",
  "dict.language.ru": "Русский",
  "dict.language.en": "English",

  "dict.country.label": "Сountry",
  "dict.country.by": "Belarus",
  "dict.country.ru": "Russia",

  "dict.request-kind.label": "Kind",
  "dict.request-kind.supply": "Supply",
  "dict.request-kind.demand": "Demand",

  "dict.request-service.label": "Service",
  "dict.request-service.companion": "Companion",
  "dict.request-service.freight": "Freight",
  "dict.request-service.passenger-traffic": "Passenger traffic",

  "dict.transport.label": "Transport",
  "dict.transport.car": "Car",
  "dict.transport.bus": "Bus",
  "dict.transport.train": "Train",
  "dict.transport.plane": "Plane",

  "list.label": "List",
  "list.emtpy": "Empty list",

  "nav.home": "Home",
  "nav.about": "About",
  "nav.requests": "Requests",
  "nav.users": "Users",
  "nav.signin": "Sign in",
  "nav.signup": "Sign up",
  "nav.profile": "Profile",

  "footer.disigned": "Designed and built by",
  "footer.using": "Using",
  "footer.and": "and",
  "footer.lang": "Interface language:",
  "footer.link.git": "Github",
  "footer.link.fb": "Facebook",
  "footer.link.vk": "VK",
  "footer.link.about": "About",
  "footer.link.autor": "Andrei Radzetski",
  "footer.link.ng2": "AngularJS 2",
  "footer.link.bootstrap": "Bootstrap 3",
  "footer.link.google-maps": "Google Maps",

  "page.home.title": "Simple Logistics",
  "page.home.description": "Some text, which describes the project.",
  "page.home.tag.add-request": "Add request",
  "page.home.tag.find-request": "Requests",
  "page.home.tag.find-user": "Users",
  "page.home.tag.about": "About system",
  "page.home.search": "Search:",
  "page.home.departure": "Departure",
  "page.home.departure-date": "Departure date",
  "page.home.destination": "Destination",
  "page.home.destination-date": "Destination date",

  "page.about.title": "About",
  "page.about.description": "Some text, which describes the section.",

  "page.users.title": "Users",
  "page.users.description": "Some text, which describes the section.",

  "page.apply.title": "Add request",
  "page.apply.description": "Some text, which describes the section.",

  "page.apply.type.label": "Type",
  "page.apply.type.kind": "Kind",
  "page.apply.type.service": "Service",

  "page.apply.attributes.label": "Attributes",
  "page.apply.attributes.places": "Количество",
  "page.apply.attributes.transport": "Вид транспорта",
  "page.apply.attributes.cargo.name": "Наименование",
  "page.apply.attributes.cargo.width": "Ширина (см)",
  "page.apply.attributes.cargo.height": "Высота (см)",
  "page.apply.attributes.cargo.length": "Длина (см)",
  "page.apply.attributes.cargo.weight": "Вес (кг)",

  "page.apply.points.label": "Points",
  "page.apply.points.name": "Name",
  "page.apply.points.radius": "Radius",
  "page.apply.points.arrival-datetime": "Date and time arrival",
  "page.apply.points.departure-datetime": "Date and time departure",
  "page.apply.points.start-point": "Start point",
  "page.apply.points.finish-point": "Finish poin",
  
  "page.apply.security.label": "Security",
  "page.apply.security.display-email": "Показывать на заявке email адрес",
  "page.apply.security.display-phone": "Показывать на заявке телефон",
  
  "page.apply.extra.label": "Extra",
  "page.apply.extra.comment": "Сomment",

  "page.login.title": "Login",
  "page.login.description": "Access to the advanced features of the system.",
  "page.login.login": "Login",
  "page.login.password": "Password",
  "page.login.remember": "Remember me",

  "page.join.title": "Join",
  "page.join.description": "Sign up - it's free!",
  "page.join.info": "After registration you will get access to the advanced capabilities of the system. The system will make it possible to be always aware of other trips for travel and carriers, and to create their own trips, travel with minimal cost.",
  "page.join.first-name": "First name",
  "page.join.second-name": "Second name",
  "page.join.email": "Email",
  "page.join.phone": "Phone",
  "page.join.password": "Password",
  "page.join.password-repeat": "Repeat password",

  "page.requests.title": "Requests",
  "page.requests.description": "Some text, which describes the section.",
  "page.requests.find.kind": "Kind",
  "page.requests.find.service": "Service",
  "page.requests.find.departure": "Departure",
  "page.requests.find.destination": "Destination",
  "page.requests.find.departure-date": "Departure date",
  "page.requests.find.destination-date": "Destination date",
  "page.requests.find.places": "Number of seats",
  "page.requests.find.transport": "Transport",

  "page.profile.title": "Profile",
  "page.profile.description": "Manage your own data and travel.",
  "page.profile.nav.info": "Info",
  "page.profile.nav.requests": "Requests",
  "page.profile.nav.messages": "Messages",
  "page.profile.nav.settings": "Settings",
  "page.profile.nav.dictionaries": "Dictionaries",
  "page.profile.nav.exit": "Exit",
  "page.profile.info.email": "Email",
  "page.profile.info.phone": "Phone",
  "page.profile.info.country": "Country",
  "page.profile.info.city": "City",
  "page.profile.info.language": "Language",
  "page.profile.info.additional": "Additional information",
  "page.profile.settings.first-name": "First name",
  "page.profile.settings.second-name": "Second name",
  "page.profile.dictionaries.type": "Type",
  "page.profile.dictionaries.key": "Key",
  "page.profile.dictionaries.value": "Value",
  "page.profile.dictionaries.description": "Description",
  "page.profile.dictionaries.translation": "Translation"
}