export const LANG_RU_NAME = 'ru';

export const LANG_RU_TRANS = {
  "appname": "Simple Logistics",

  "button.save": "Сохранить",
  "button.login": "Войти",
  "button.signup": "Зарегистрироваться",
  "button.apply": "Добавить заявку",
  "button.search": "Поиск",
  "button.next": "Далее",
  "button.add": "Добавить",

  "lang.ru": "Русский",
  "lang.en": "English",

  "nav.home": "Главная",
  "nav.about": "О системе",
  "nav.requests": "Запросы",
  "nav.users": "Пользователи",
  "nav.signin": "Вход",
  "nav.signup": "Регистрация",
  "nav.profile": "Профиль",
  
  "footer.disigned": "Спроектировал и разработал",
  "footer.using": "С использованием",
  "footer.and": "и",
  "footer.lang": "Язык интерфейса:",
  "footer.link.git": "Github",
  "footer.link.fb": "Facebook",
  "footer.link.vk": "ВКонтакте",
  "footer.link.about": "О системе",
  "footer.link.autor": "Андрей Радецкий",
  "footer.link.ng2": "AngularJS 2",
  "footer.link.bootstrap": "Bootstrap 3",
  "footer.link.google-maps": "Google Maps",

  "page.home.title": "Simple Logistics",
  "page.home.description": "Какой-то текст, который описывает проект.",
  "page.home.tag.add-request": "Добавить заявку",
  "page.home.tag.find-request": "Найти заявку",
  "page.home.tag.find-user": "Найти пользователя",
  "page.home.tag.about": "О системе",
  "page.home.search": "Поиск:",
  "page.home.departure": "Пункт отправления",
  "page.home.departure-date": "Дата отправления",
  "page.home.destination": "Пункт назначения",
  "page.home.destination-date": "Дата назначения",

  "page.about.title": "О системе",
  "page.about.description": "Какой-то текст, который описывает раздел.",

  "page.users.title": "Пользователи",
  "page.users.description": "Какой-то текст, который описывает раздел.",

  "page.apply.title": "Добавить заявку",
  "page.apply.description": "Какой-то текст, который описывает раздел.",

  "page.apply.type.label": "Тип",
  "page.apply.type.kind": "Вид",
  "page.apply.type.service": "Услуга",

  "page.apply.attributes.label": "Атрибуты",
  "page.apply.attributes.places": "Количество",
  "page.apply.attributes.transport": "Вид транспорта",
  "page.apply.attributes.cargo.name": "Наименование",
  "page.apply.attributes.cargo.width": "Ширина (см)",
  "page.apply.attributes.cargo.height": "Высота (см)",
  "page.apply.attributes.cargo.length": "Длина (см)",
  "page.apply.attributes.cargo.weight": "Вес (кг)",

  "page.apply.points.label": "Точки",
  "page.apply.points.name": "Название",
  "page.apply.points.radius": "Радиус",
  "page.apply.points.arrival-datetime": "Дата и время прибытия",
  "page.apply.points.departure-datetime": "Дата и время отбытия",
  "page.apply.points.start-point": "Начальная точка",
  "page.apply.points.finish-point": "Конечная точка",

  "page.apply.security.label": "Безопасность",
  "page.apply.security.display-email": "Показывать на заявке email адрес",
  "page.apply.security.display-phone": "Показывать на заявке телефон",

  "page.apply.extra.label": "Дополнительно",
  "page.apply.extra.comment": "Комментарий",

  "page.login.title": "Вход",
  "page.login.description": "Какой-то текст, который описывает раздел.",
  "page.login.login": "Логин",
  "page.login.password": "Пароль",
  "page.login.remember": "Запомнить меня",

  "page.join.title": "Регистрация",
  "page.join.description": "Какой-то текст, который описывает раздел.",
  "page.join.info": "Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел. Какой-то текст, который описывает раздел.",
  "page.join.first-name": "Имя",
  "page.join.second-name": "Фамилия",
  "page.join.email": "Почта",
  "page.join.phone": "Телефон",
  "page.join.password": "Пароль",
  "page.join.password-repeat": "Повторите пароль",

  "page.requests.title": "Запросы",
  "page.requests.description": "Какой-то текст, который описывает раздел.",

  "page.profile.title": "Профиль",
  "page.profile.description": "Какой-то текст, который описывает раздел.",
  "page.profile.nav.info": "Информация",
  "page.profile.nav.requests": "Запросы",
  "page.profile.nav.messages": "Сообщения",
  "page.profile.nav.settings": "Настройки",
  "page.profile.info.email": "Почта",
  "page.profile.info.phone": "Телефон",
  "page.profile.info.country": "Страна",
  "page.profile.info.city": "Город",
  "page.profile.info.language": "Язык",
  "page.profile.info.additional": "Дополнительная информация",
  "page.profile.settings.first-name": "Имя",
  "page.profile.settings.second-name": "Фамилия"
  
}